//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Personkartotek
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Person
	{
		public virtual string Fornavn
		{
			get;
			set;
		}

		public virtual string Efternavn
		{
			get;
			set;
		}

		public virtual string Mellemnavn
		{
			get;
			set;
		}

		public virtual int PersonID
		{
			get;
			set;
		}

		public virtual string PersonType
		{
			get;
			set;
		}

		public virtual IEnumerable<Telefon> Telefon
		{
			get;
			set;
		}

		public virtual Adresse Folkeregisteradresse
		{
			get;
			set;
		}

		public virtual IEnumerable<AdresseAlternativ> AdresseAlternativ
		{
			get;
			set;
		}

	}
}

