//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Personkartotek
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Telefon
	{
		public virtual int Telefonnummer
		{
			get;
			set;
		}

		public virtual int TelefonID
		{
			get;
			set;
		}

		public virtual string TelefonType
		{
			get;
			set;
		}

		public virtual int PersonID
		{
			get;
			set;
		}

		public virtual Person Person
		{
			get;
			set;
		}

	}
}

