--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 30 2016 09:39
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'Adresse'   
-- AdresseID       :  
-- Vejnavn         :  
-- Husnummer       :  
-- Postnummer      :  
-- Bynavn          :  
--
CREATE TABLE Adresse (
    AdresseID      BIGINT IDENTITY(1,1) NOT NULL,
    Vejnavn        NVARCHAR(300) NOT NULL,
    Husnummer      NVARCHAR(300) NOT NULL,
    Postnummer     NVARCHAR(300) NOT NULL,
    Bynavn         NVARCHAR(300) NOT NULL,
CONSTRAINT pk_Adresse PRIMARY KEY CLUSTERED (AdresseID))