--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 30 2016 09:15
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'db_name'
--
USE db_name
GO
 
IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Create Table    : 'Adresse'   
-- AdresseID       :  
-- Vejnavn         :  
-- Husnummer       :  
-- Postnummer      :  
-- Bynavn          :  
--
CREATE TABLE Adresse (
    AdresseID      BIGINT IDENTITY(1,1) NOT NULL,
    Vejnavn        NVARCHAR(300) NOT NULL,
    Husnummer      NVARCHAR(300) NOT NULL,
    Postnummer     NVARCHAR(300) NOT NULL,
    Bynavn         NVARCHAR(300) NOT NULL,
CONSTRAINT pk_Adresse PRIMARY KEY CLUSTERED (AdresseID))
GO

--
-- Create Table    : 'Person'   
-- PersonID        :  
-- Fornavn         :  
-- Mellemnavn      :  
-- Efternavn       :  
-- PersonType      :  
-- AdresseID       :  (references Adresse.AdresseID)
--
CREATE TABLE Person (
    PersonID       BIGINT IDENTITY(1,1) NOT NULL,
    Fornavn        NVARCHAR(300) NOT NULL,
    Mellemnavn     NVARCHAR(300) NOT NULL,
    Efternavn      NVARCHAR(300) NOT NULL,
    PersonType     NVARCHAR(300) NOT NULL,
    AdresseID      BIGINT NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (PersonID),
CONSTRAINT fk_Person FOREIGN KEY (AdresseID)
    REFERENCES Adresse (AdresseID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Telefon'   
-- TelefonID       :  
-- Telefonnummer   :  
-- TelefonType     :  
-- PersonID        :  (references Person.PersonID)
--
CREATE TABLE Telefon (
    TelefonID      BIGINT IDENTITY(1,1) NOT NULL,
    Telefonnummer  NVARCHAR(300) NOT NULL,
    TelefonType    NVARCHAR(300) NOT NULL,
    PersonID       BIGINT NOT NULL,
CONSTRAINT pk_Telefon PRIMARY KEY CLUSTERED (TelefonID),
CONSTRAINT fk_Telefon FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'AlternativAdresse'   
-- PersonID        :  (references Person.PersonID)
-- AdresseID       :  (references Adresse.AdresseID)
-- AdresseType     :  
--
CREATE TABLE AlternativAdresse (
    PersonID       BIGINT NOT NULL,
    AdresseID      BIGINT NOT NULL,
    AdresseType    NVARCHAR(300) NOT NULL,
CONSTRAINT pk_AlternativAdresse PRIMARY KEY CLUSTERED (PersonID,AdresseID),
CONSTRAINT fk_AlternativAdresse FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_AlternativAdresse2 FOREIGN KEY (AdresseID)
    REFERENCES Adresse (AdresseID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Adresse TO public
GO
GRANT ALL ON Person TO public
GO
GRANT ALL ON Telefon TO public
GO
GRANT ALL ON AlternativAdresse TO public
GO

