--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 30 2016 09:39
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Drop Table    : 'AlternativAdresse'   
--
DROP TABLE AlternativAdresse
GO
--
-- Drop Table    : 'Telefon'   
--
DROP TABLE Telefon
GO
--
-- Drop Table    : 'Person'   
--
DROP TABLE Person
GO
--
-- Drop Table    : 'Adresse'   
--
DROP TABLE Adresse
GO
